version: '3'

services:
  photos:
    build: .
    command: "npm run load"
    depends_on:
      - "database"
    ports:
      - "3002:3002"
  database:
    container_name: database
    image: mongo:latest
    ports:
      - "27017:27017"
